// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Dashing.Alarm = (function(superClass) {
    extend(Alarm, superClass);

    function Alarm() {
      return Alarm.__super__.constructor.apply(this, arguments);
    }

    Alarm.accessor('send_sms', Dashing.AnimatedValue);

    Alarm.accessor('send_mail', Dashing.AnimatedValue);

    Alarm.accessor('send_icon', function() {
      if (this.get('title') === 'ASJ') {
        return 'fa fa-envelope';
      } else {
        return 'fa fa-commenting';
      }
    });

    Alarm.prototype.ready = function() {};

    Alarm.prototype.onData = function(data) {};

    return Alarm;

  })(Dashing.Widget);

}).call(this);
