version: '3.8'

services:
  smashing:
    build: .
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=test-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Password@123
      - DB_DATABASE=RPA_Dashboard
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network:
    external: true


