services:
  smashing:
    build: .
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=192.168.0.125
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Password@123
      - DB_DATABASE=RPA_Dashboard
    volumes:
      - .:/app
    networks:
      - custom_network
networks:
  custom_network:
    external: true

